name: CI-CD - Build Docker, Push to GHCR & Deploy Render

on:
  push:
    branches: ["master"]  # Se ejecuta en cada push a main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # IMPORTANTE para subir imagen a GHCR

    steps:

      # 1) Descargar repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Login al Registry de GitHub (GHCR)
      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 3) Construir imagen Docker
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/app:latest .

      # 4) Push de image a GHCR
      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.repository }}/app:latest

      # 5) Trigger despliegue autom√°tico en Render
      - name: Deploy to Render from Image
        run: |
          curl -X POST -sS \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
                "imagePath": "ghcr.io/${{ github.repository }}/app:latest"
              }' \
           https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
