name: CI - Build & Push to GHCR

on:
  push:
    branches: [ "master" ] # O main si ese es tu branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      # üî• AQU√ç YA NO HAY "" VAC√çO ‚Äî USA TU SECRET
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/lab17a:latest .

      - name: Push Image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/lab17a:latest
